services:
  user:
    build:
      target: development
    command: bun dev --filter=@peerprep/user-service
    volumes:
      - ./services/user-service:/app/services/user-service

  questions:
    build:
      target: development
    command: bun dev --filter=@peerprep/questions-service
    volumes:
      - ./services/questions-service:/app/services/questions-service

  matching:
    build:
      target: development
    command: bun dev --filter=@peerprep/matching-service
    volumes:
      - ./services/matching-service:/app/services/matching-service

  collaboration:
    build:
      target: development
    command: bun dev --filter=@peerprep/collaboration-service
    volumes:
      - ./services/collaboration-service:/app/services/collaboration-service

  ai:
    build:
      target: development
    command: bun dev --filter=@peerprep/ai-service
    volumes:
      - ./services/ai-service:/app/services/ai-service

  frontend:
    build:
      target: development
    command: bun dev --filter=peerprep
    volumes:
      - ./apps/peerprep:/app/apps/peerprep

  admin-portal:
    build:
      target: development
    command: bun dev --filter=@peerprep/admin-portal
    volumes:
      - ./apps/admin-portal:/app/apps/admin-portal
