name: Build and lint
jobs:
  my-job:
    name: my-job
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve the repository code
        uses: actions/checkout@v4
      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install
      - name: Build projects
        run: bun run build
      - name: Lint projects
        run: bun run lint
